title: Ray Chang
email: ray120424@gmail.com
description: >- 
 這是我的個人網站，裡面詳細的介紹了我從小到大的經歷、做過的事情，還有現在以及未來的發展。
baseurl: /activity_reflections 
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - robot/機器人.md
  - sailing/帆船.md
  - bicycle/腳踏車.md
  - learning_schedule/學習進度規劃.md
  - bus/公車.md
  - program/程式.md