title: Ray Chang
email: ray120424@gmail.com
description: >- 
 這是我的個人網站，裡面詳細的介紹了我從小到大的經歷、做過的事情，還有現在以及未來的發展。
baseurl: /activity_reflections 
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - 機器人.md
  - 帆船.md
  - 腳踏車.md
  - 學習進度規劃.md
  - 公車.md
  - 程式.md